# kubetpl:syntax:$

# kubetpl:set:NAMESPACE=default
---
apiVersion: v1
kind: Service
metadata:
  name: $NAME
  namespace: $NAMESPACE
  labels:
    app: $NAME
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: $NAME-$VERSION
